// <auto-generated/>
using Microsoft.AspNetCore.Components;
using RawiReport.Apps.Apps.ReportApps;
using RawiReport.Domains.Models.Reports;

namespace RawiReportUI.Modals.ReportsDaily;

public partial class ReportStaticInfoModal
{
 


    [Parameter]
    public EventCallback<bool> IsOpenChanged { get; set; }

    [Parameter]
    public EventCallback<ReportStaticInfoModel> OnSubmit { get; set; }

    [Parameter] public Guid ReportId { get; set; }
    [Inject] public IReportsServices reportsServices { get; set; }
    public ReportStaticInfoModel FormModel { get; set; } = new();

    public bool IsOpen = false;
    private async Task HandleSubmit()
    {

        foreach(var item in FormModel.RawMaterials)
        {
            var Consumption = new ReportConsumptionModel
            {
                Id = Guid.NewGuid(),
                ReportId = ReportId,
                MatierePremiere = item.MatierePremiere,
                Supplier = item.Supplier,
                Quantity = item.Quantity,
                Loss = item.Loss,
                Remark = item.Remark
            };
            await reportsServices.CreateConsumption(Consumption);
        }

        var losse = new ReportLosseModel
        {
            Id = Guid.NewGuid(),
            ReportId = ReportId,
            Bottles = FormModel.Bottles,
            PreformeSouffleuse = FormModel.PreformeSouffleuse,
            PostformeSouffleuse = FormModel.PostformeSouffleuse,
            Palettes = FormModel.Palettes,
            TotalPalettes = FormModel.TotalPalettes,
            TotalFardeaux = FormModel.TotalFardeaux

        };
        await reportsServices.CreateLosses(losse);
        
        await reportsServices.ChangeReportState(ReportId, ReportStatus.Disabled);
        await OnSubmit.InvokeAsync(FormModel);
        await close();
    }

    private async Task close()
    {
        IsOpen = false;
        StateHasChanged();
    }

    public async Task ShowModal()
    {
        IsOpen = true;
        StateHasChanged();
    }

    protected override void OnInitialized()
    {
        FormModel.RawMaterials = new List<ReportStaticInfoModel>
        {
            new ReportStaticInfoModel { MatierePremiere = "Preforme" },
            new ReportStaticInfoModel { MatierePremiere = "Etiquettes" },
            new ReportStaticInfoModel { MatierePremiere = "Film thermo" },
            new ReportStaticInfoModel { MatierePremiere = "Bande adhesif" },
            new ReportStaticInfoModel { MatierePremiere = "Interaclaire" },
            new ReportStaticInfoModel { MatierePremiere = "Colle a chaud" },
            new ReportStaticInfoModel { MatierePremiere = "Bouchons" },
            new ReportStaticInfoModel { MatierePremiere = "Film etirable" },
        };
    }
}